#!/bin/sh

set -o errexit
set -o nounset

xcf_filename="$1"
readonly xcf_filename

png_filename="$2"
readonly png_filename

script_dir_pathname="$(dirname -- "$0")"
readonly script_dir_pathname

sed -e s%'{{FILENAME_XCF}}'%"$xcf_filename"%g \
    -e s%'{{FILENAME_PNG}}'%"$png_filename"%g \
    "$script_dir_pathname/gimp-export-png-batch-commands.py" |
	gimp --new-instance --no-interface --batch-interpreter python-fu-eval --batch -
